ALTER TABLE deployments
  DROP CONSTRAINT deployments_status_check;

ALTER TABLE deployments
  ADD CONSTRAINT deployments_status_check
  CHECK (status IN (
    'QUEUED', 'VALIDATING', 'CLONING', 'BUILDING',
    'PUSHING_IMAGE', 'DEPLOYING', 'RUNNING', 'FAILED'
  ));

ALTER TABLE deployments
  ALTER COLUMN status SET DEFAULT 'QUEUED',
  ALTER COLUMN stage SET DEFAULT 'QUEUED';

ALTER TABLE deployments
  ADD CONSTRAINT deployments_stage_check
  CHECK (stage IN (
    'QUEUED', 'VALIDATING_REPOSITORY', 'CLONING_REPOSITORY',
    'DETECTING_TECHNOLOGY', 'INSTALLING_DEPENDENCIES',
    'BUILDING_APPLICATION', 'CREATING_IMAGE', 'AUTHENTICATING_REGISTRY',
    'PUSHING_IMAGE', 'APPLYING_KUBERNETES_DEPLOYMENT', 'CREATING_SERVICE',
    'CREATING_INGRESS', 'VERIFYING_ROLLOUT', 'GENERATING_LIVE_URL', 'RUNNING'
  ));

ALTER TABLE deployments
  ADD CONSTRAINT deployments_status_stage_check
  CHECK (
    (status = 'QUEUED' AND stage = 'QUEUED')
    OR (status = 'VALIDATING' AND stage = 'VALIDATING_REPOSITORY')
    OR (status = 'CLONING' AND stage = 'CLONING_REPOSITORY')
    OR (status = 'BUILDING' AND stage IN (
      'DETECTING_TECHNOLOGY', 'INSTALLING_DEPENDENCIES',
      'BUILDING_APPLICATION', 'CREATING_IMAGE'
    ))
    OR (status = 'PUSHING_IMAGE' AND stage IN ('AUTHENTICATING_REGISTRY', 'PUSHING_IMAGE'))
    OR (status = 'DEPLOYING' AND stage IN (
      'APPLYING_KUBERNETES_DEPLOYMENT', 'CREATING_SERVICE', 'CREATING_INGRESS',
      'VERIFYING_ROLLOUT', 'GENERATING_LIVE_URL'
    ))
    OR (status = 'RUNNING' AND stage = 'RUNNING')
    OR (status = 'FAILED' AND stage IN (
      'QUEUED', 'VALIDATING_REPOSITORY', 'CLONING_REPOSITORY',
      'DETECTING_TECHNOLOGY', 'INSTALLING_DEPENDENCIES',
      'BUILDING_APPLICATION', 'CREATING_IMAGE', 'AUTHENTICATING_REGISTRY',
      'PUSHING_IMAGE', 'APPLYING_KUBERNETES_DEPLOYMENT', 'CREATING_SERVICE',
      'CREATING_INGRESS', 'VERIFYING_ROLLOUT', 'GENERATING_LIVE_URL'
    ))
  );

ALTER TABLE deployments
  ADD CONSTRAINT deployments_running_live_url_check
  CHECK (status <> 'RUNNING' OR NULLIF(BTRIM(live_url), '') IS NOT NULL);

ALTER TABLE deployments
  ADD CONSTRAINT deployments_failed_live_url_check
  CHECK (status <> 'FAILED' OR live_url IS NULL);
